### ISSUE TITLE
[BUG] HTTP Status 400 – Bad Request

### ISSUE THREAD

**Issue by BlueCoffee34** [linuxserver/docker-airsonic-advanced#21] opened 2023-10-29 13:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Changing admin password or making a new user

### Expected Behavior

It should change the password or make the new user

But I get this

`HTTP Status 400 – Bad Request

Type Exception Report

Message Request header is too large

Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

Exception

java.lang.IllegalArgumentException: Request header is too large
	org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:790)
	org.apache.coyote.http11.Http11InputBuffer.parseHeader(Http11InputBuffer.java:899)
	org.apache.coyote.http11.Http11InputBuffer.parseHeaders(Http11InputBuffer.java:604)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:294)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base/java.lang.Thread.run(Thread.java:829)

Note The full stack trace of the root cause is available in the server logs.
Apache Tomcat/9.0.60`

### Steps To Reproduce

Make a new user and hit save

### Environment

```markdown
- OS: OMV
- How docker service was installed: OMV
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  airsonic-advanced:
    image: lscr.io/linuxserver/airsonic-advanced:latest
    container_name: airsonic-advanced
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CONTEXT_PATH= #optional
      - JAVA_OPTS= #optional
    volumes:
      - /srv/dev-disk-by-uuid-735cc309-fa91-4d6e-b8af-cd73f972ec7f/Data/DockerData/AirSonic:/config
      - /srv/dev-disk-by-uuid-0386aa39-24c1-4f38-bd21-ff3d49b4d959/Audio/Music:/music
      - /srv/dev-disk-by-uuid-0386aa39-24c1-4f38-bd21-ff3d49b4d959/Audio/Playlists:/playlists
      - /srv/dev-disk-by-uuid-0386aa39-24c1-4f38-bd21-ff3d49b4d959/Audio/Podcasts:/podcasts
    ports:
      - 4040:4040
    devices:
      - /dev/snd:/dev/snd #optional
    restart: unless-stopped
```

### Container logs

```bash
No error shown in logs
```

**Comment by BlueCoffee34** [comment] 2023-10-29 13:13
> A human has marked this issue as invalid, this likely happened because the issue template was not used in the creation of the issue.

I have no idea what this even means. Why is it Invalid?

**Comment by BlueCoffee34** [comment] 2023-10-29 16:11
From Dozzle logs

`10/29/2023
04:09:26 PM
2023-10-29 16:09:26.358  WARN --- o.a.p.u.LegacyHsqlMigrationUtil          : Failed to determine HSQLDB database version
10/29/2023
04:09:26 PM
10/29/2023
04:09:26 PM
java.io.FileNotFoundException: /config/db/airsonic.properties
10/29/2023
04:09:26 PM
	at org.springframework.core.io.FileSystemResource.getInputStream(FileSystemResource.java:189) ~[spring-core-5.3.18.jar!/:5.3.18]
10/29/2023
04:09:26 PM
	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:144) ~[spring-core-5.3.18.jar!/:5.3.18]
10/29/2023
04:09:26 PM
	at org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties(PropertiesLoaderUtils.java:133) ~[spring-core-5.3.18.jar!/:5.3.18]
10/29/2023
04:09:26 PM
	at org.airsonic.player.util.LegacyHsqlMigrationUtil.getHsqlDbVersion(LegacyHsqlMigrationUtil.java:31) ~[classes!/:11.0.0-SNAPSHOT]
10/29/2023
04:09:26 PM
	at org.airsonic.player.util.LegacyHsqlMigrationUtil.isHsqlDbBackupNeeded(LegacyHsqlMigrationUtil.java:64) ~[classes!/:11.0.0-SNAPSHOT]
10/29/2023
04:09:26 PM
	at org.airsonic.player.util.LegacyHsqlMigrationUtil.upgradeFileHsqlDbIfNeeded(LegacyHsqlMigrationUtil.java:159) ~[classes!/:11.0.0-SNAPSHOT]
10/29/2023
04:09:26 PM
	at org.airsonic.player.spring.StartupEventListener.onApplicationEvent(StartupEventListener.java:17) ~[classes!/:11.0.0-SNAPSHOT]
10/29/2023
04:09:26 PM
	at org.airsonic.player.spring.StartupEventListener.onApplicationEvent(StartupEventListener.java:1) ~[classes!/:11.0.0-SNAPSHOT]
10/29/2023
04:09:26 PM
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.18.jar!/:5.3.18]
10/29/2023
04:09:26 PM
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.18.jar!/:5.3.18]
10/29/2023
04:09:26 PM
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.18.jar!/:5.3.18]
10/29/2023
04:09:26 PM
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.18.jar!/:5.3.18]
10/29/2023
04:09:26 PM
	at org.springframework.boot.context.event.EventPublishingRunListener.contextPrepared(EventPublishingRunListener.java:89) ~[spring-boot-2.5.12.jar!/:2.5.12]
10/29/2023
04:09:26 PM
	at org.springframework.boot.SpringApplicationRunListeners.lambda$contextPrepared$3(SpringApplicationRunListeners.java:67) ~[spring-boot-2.5.12.jar!/:2.5.12]
10/29/2023
04:09:26 PM
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
10/29/2023
04:09:26 PM
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.12.jar!/:2.5.12]
10/29/2023
04:09:26 PM
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.12.jar!/:2.5.12]
10/29/2023
04:09:26 PM
	at org.springframework.boot.SpringApplicationRunListeners.contextPrepared(SpringApplicationRunListeners.java:67) ~[spring-boot-2.5.12.jar!/:2.5.12]
10/29/2023
04:09:26 PM
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:418) ~[spring-boot-2.5.12.jar!/:2.5.12]
10/29/2023
04:09:26 PM
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.12.jar!/:2.5.12]
10/29/2023
04:09:26 PM
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:143) ~[spring-boot-2.5.12.jar!/:2.5.12]
10/29/2023
04:09:26 PM
	at org.airsonic.player.Application.main(Application.java:70) ~[classes!/:11.0.0-SNAPSHOT]
10/29/2023
04:09:26 PM
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
10/29/2023
04:09:26 PM
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
10/29/2023
04:09:26 PM
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
10/29/2023
04:09:26 PM
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
10/29/2023
04:09:26 PM
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[airsonic.war:11.0.0-SNAPSHOT]
10/29/2023
04:09:26 PM
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[airsonic.war:11.0.0-SNAPSHOT]
10/29/2023
04:09:26 PM
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[airsonic.war:11.0.0-SNAPSHOT]
10/29/2023
04:09:26 PM
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) ~[airsonic.war:11.0.0-SNAPSHOT]`

**Comment by j0nnymoe** [comment] 2023-10-29 16:13
Could you provide the container start up logs? that's what's missing.

**Comment by BlueCoffee34** [comment] 2023-10-29 16:15
> Could you provide the container start up logs? that's what's missing.

Sorry new to all this is this the start up logs?
[startup.txt](https://github.com/linuxserver/docker-airsonic-advanced/files/13198571/startup.txt)

**Comment by drizuid** [comment] 2023-11-19 00:19
it looks like a database issue, but i dont use this container, so am only going off the logs.

**Comment by krp312** [comment] 2024-01-19 10:25
seeing the same error, but not the same cause: `java.io.FileNotFoundException: /config/db/airsonic.properties`

i'm using dockstarter's airsonic-advanced image. i simply spin up the container, and i'm getting a 404: 
<img width="744" alt="Screenshot 2024-01-19 at 5 24 32 AM" src="https://github.com/linuxserver/docker-airsonic-advanced/assets/16083866/b945a0b6-43f4-4123-be30-af0d4d23e594">

container log: [iTerm2 Session Jan 19, 2024 at 5:21:08 AM.txt](https://github.com/linuxserver/docker-airsonic-advanced/files/13987754/iTerm2.Session.Jan.19.2024.at.5.21.08.AM.txt)

any help is much appreciated

**Comment by homerr** [comment] 2024-03-17 13:04
I cannot reproduce this error, I note that the original was created with OMV and with two different disks in use - possibly causing the issues.

Second commenter notes about the `airsonic.properties` - I also had this before it then created and the container starts. Might be worth checking uid/gid settings for the creation of the container. 

Other than that, it works alright so closing this down

**Closed by homerr** 2024-03-17 13:04 UTC
Labels: no-issue-activity
